
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const RENDER_TO_CART = 'RENDER_TO_CART'
export const CART_COST = 'CART_COST'
export const WALLET_BALANCE = 'WALLET_BALANCE'
export const WALLET_REDUCE = 'WALLET_REDUCE'